trigger:
 branches:
   include:
     - main
pool: agent-pool
variables:
- group: New variable group 03-Jun
- name: agent
  value: agent-pool
parameters:
- name: env
  displayName: select environment
  values:
    - dev
    - UAT
    - prod
  default: dev
- name: runapply
  displayName: Run Apply?
  type: boolean
  default: false
stages:
- stage: planstage
  jobs:
  - job: inittoplnjob
    steps:
    