trigger:
 branches:
   include:
     - main
pool: agent-pool
variables:
- group: New variable group 03-Jun
- name: agent
  value: agent-pool
parameters:
- name: env
  displayName: select environment
  values:
    - dev
    - UAT
    - prod
  default: dev
- name: runapply
  displayName: Run Apply?
  type: boolean
  default: false
stages:
- stage: planstage
  jobs:
  - job: installinstalljob
    steps:
    - task: TerraformInstaller@1
      displayName: terraform install
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      displayName: terraform init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environment /dev/'
        backendServiceArm: 'Azure subscription 1 (34cc9902-c707-4432-93a5-d466f2a325ab)'
        backendAzureRmOverrideSubscriptionID: '34cc9902-c707-4432-93a5-d466f2a325ab'
        backendAzureRmResourceGroupName: 'edfusion-rg'
        backendAzureRmStorageAccountName: 'stg233001'
        backendAzureRmContainerName: 'container'
        backendAzureRmKey: 'dev.terraform.tfstate'